In [1]:
import numpy as np

a = np.array([1, 2, 3])

In [2]:
print(type(a))

<class 'numpy.ndarray'>


In [3]:
print(a.shape)

(3,)


In [4]:
print(a[0],a[1],a[2])

1 2 3


In [7]:
a[0] = 5
print(a)

[5 2 3]


In [8]:
b = np.array([[1,2,3],[4,5,6]])
print(b.shape)

(2, 3)


In [9]:
print(b[0,0], b[0,1], b[1, 0])

1 2 4


In [10]:
import numpy as np

a = np.zeros((2, 2)) # 전체가 0인 배열 생성 zeros
print(a)

b = np.ones((1, 2)) # 전체가 1인 배열 생성 ones
print(b)

c = np.full((2, 2), 7) # 전체가 n인 배열 생성 full
print(c)

d = np.eye(2) # 2x2 단위행렬 생성
print(d)

e = np.random.random((2,2)) #(0~1) 사이의 임의의 값으로 배열 생성
print(e)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.15020654 0.76663677]
 [0.75467507 0.40375571]]


In [12]:
import numpy as np

a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

b = a[:2, 1:3] # a 배열에서 0행부터 2행 이전까지, 1열 부터 3열 이전까지
print(b)

print(a[0,1]) # 2가 출력됨
b[0,0] = 77 #b[0,0] == a[0,1]
print(a[0,1]) #값의 변화가 존재

#a와 b는 복사된 것이 아닌 연결이 되어있음을 알 수 있다

[[2 3]
 [6 7]]
2
77


In [15]:
import numpy as np

a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

row_r1 = a[1, :] #행을 선택하는 곳에서 인덱싱을 함 => 2차원에서 1차원데이터 로의 변화
row_r2 = a[1:2, :] # 인덱싱 대신 슬라이싱을 함 => 2차원 배열이 그대로 유지
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)

#열 또한 마찬가지
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [2]:
import numpy as np

x = np.array([1, 2])
print(x.dtype)

x = np.array([1.0, 2.0])
print(x.dtype)

x = np.array([1.0, 2.0], dtype=np.int64)
print(x, x.dtype)

int32
float64
[1 2] int64


In [1]:
import pandas
pandas.__version__

'1.2.3'

In [2]:
a = [1, 2, 3]
print(a + 1)

TypeError: can only concatenate list (not "int") to list

In [3]:
import numpy as np

x = np.array([1, 2])
print(x + 1)

[2 3]


In [4]:
import numpy as np

x = np.array([1, 2])
y = 1
print(x.dtype, y.dtype)

AttributeError: 'int' object has no attribute 'dtype'